#!/bin/bash

DIALOG=${DIALOG=dialog}

tempfile=`mktemp 2>/dev/null` || tempfile=/tmp/test$$
trap "rm -f $tempfile" 0 1 2 5 15

InfoDialog() {
    $DIALOG --msgbox "$1" 5 70
}

SetSerial() {
    stty 9600 cs8 cstopb -parenb -F /dev/ttyS0
}

Floppy() {
	mkdir -p /mnt/fdd

	mkdir -p /mnt/fdd/F80

    mount /dev/sda /mnt/fdd

    cd /mnt/fdd

	cp *.F80 ./F80

	cd ./F80

    local list=""
    local i=1
    for file in *; do
	list="$list $file $i"
	((i++))
    done

	sleep 1

	$DIALOG --infobox "Wait" 5 70

    $DIALOG --title "Select file" --menu "" 20 51 5 \
    ${list} 2> ${tempfile}

    local retval=$?

    local namefile=`cat $tempfile`

	case $retval in
	1)
	    Dialog
	    ;;
	255)
	    Dialog
	    ;;
    esac

    SetSerial

    cat /M/ERASE > /dev/ttyS0

    (
    b=10
    while [ $b -ne 110 ]
    do
        echo $b
        ((b+=10))
        sleep 12
    done
    ) |
    dialog --title "The file is sent" --gauge "Please wait ...." 10 60 0

    cat /M/WRITE > /dev/ttyS0

    cat $namefile > /dev/ttyS0

    cat /M/END > /dev/ttyS0

    InfoDialog "The file $namefile was sent"

	cd /mnt

	umount /mnt/fdd

	rm -rf ./fdd
}

Flash() {
    mkdir -p /mnt/flash

	mkdir -p /mnt/flash/F80

    mount /dev/sda1 /mnt/flash

    cd /mnt/flash

	cp *.F80 ./F80

	cd ./F80

    local list=""
    local i=1
    for file in *; do
	list="$list $file $i"
	((i++))
    done

	sleep 1

    $DIALOG --title "Select file" --menu "" 20 51 5 \
    ${list} 2> ${tempfile}

	local retval=$?

    local namefile=`cat $tempfile`

	case $retval in
	1)
	    Dialog
	    ;;
	255)
	    Dialog
	    ;;
    esac

    SetSerial

	cat /M/ERASE > /dev/ttyS0

    (
    c=10
    while [ $c -ne 110 ]
    do
        echo $c
        ((c+=10))
        sleep 12
    done
    ) |
    dialog --title "The file is sent" --gauge "Please wait ...." 10 60 0

	cat /M/WRITE > /dev/ttyS0

    cat $namefile > /dev/ttyS0

    cat /M/END > /dev/ttyS0
    
    InfoDialog "The file $namefile was sent"

	cd /mnt

	umount /mnt/flash

	rm -rf ./flash
}

Dialog() {
    $DIALOG --title "Select the device" --menu "" 20 51 4 \
    "1" "Flash" \
    "2" "Floppy" 2> $tempfile

    local retval=$?

    local choise=`cat $tempfile`

    case $retval in
	0)
	    if [ $choise = "1" ]; then
		Flash
		Dialog
	    else
		Floppy
		Dialog
	    fi
	    Dialog
	    ;;
	1)
	    Dialog
	    ;;
	255)
	    Dialog
	    ;;
    esac
}

SetSerial
Dialog