#!/bin/bash

DIALOG=${DIALOG=dialog}

tempfile=`mktemp 2>/dev/null` || tempfile=/tmp/test$$
trap "rm -f $tempfile" 0 1 2 5 15

InfoDialog() {
    $DIALOG --msgbox "$1" 5 70
}

SetSerial() {
    stty 9600 cs8 cstopb -parenb -F /dev/ttyS0
}

Floppy() {
    mkdir -p /mnt/fdd

    mount /dev/sdb /mnt/fdd

    cd /mnt/fdd

    local list=""
    local i=1
    for file in *; do
	list="$list $file $i"
	((i++))
    done

    $DIALOG --title "Select file" --menu "" 20 51 5 \
    ${list} 2> ${tempfile}

    local namefile=`cat $tempfile`

    SetSerial

    echo 'A1' > /dev/ttyS0
    echo 'A1' > /dev/ttyS0
    echo 'A1' > /dev/ttyS0

    (
    b=10
    while [ $b -ne 110 ]
    do
        echo $b
        ((b+=10))
        sleep 12
    done
    ) |
    dialog --title "The file is sent" --gauge "Please wait ...." 10 60 0

    echo 'C1' > /dev/ttyS0
    echo 'C1' > /dev/ttyS0
    echo 'C1' > /dev/ttyS0

    cat $namefile > /dev/ttyS0

    echo '0D' > /dev/ttyS0

    InfoDialog "The file $namefile was sent"

    umount /mnt/floppy
    
    InfoDialog "The floppy can be removed"
}

Flash() {
    mkdir -p /mnt/sdb

    mount /dev/sdb /mnt/sdb

    cd /mnt/sdb

    local list=""
    local i=1
    for file in *; do
	list="$list $file $i"
	((i++))
    done

    $DIALOG --title "Select file" --menu "" 20 51 5 \
    ${list} 2> ${tempfile}

    local namefile=`cat $tempfile`

    SetSerial

    echo 'A1' > /dev/ttyS0
    echo 'A1' > /dev/ttyS0
    echo 'A1' > /dev/ttyS0

    (
    c=10
    while [ $c -ne 110 ]
    do
        echo $c
        ((c+=10))
        sleep 12
    done
    ) |
    dialog --title "The file is sent" --gauge "Please wait ...." 10 60 0

    echo 'C1' > /dev/ttyS0
    echo 'C1' > /dev/ttyS0
    echo 'C1' > /dev/ttyS0

    cat $namefile > /dev/ttyS0

    echo '0D' > /dev/ttyS0
    
    InfoDialog "The file $namefile was sent"

    umount /mnt/flash

    InfoDialog "The flash can be removed"
}

Dialog() {
    $DIALOG --title "Select the device" --menu "" 20 51 4 \
    "1" "Floppy" \
    "2" "Flash" 2> $tempfile

    local retval=$?

    local choise=`cat $tempfile`

    case $retval in
	0)
	    if [ $choise = "1" ]; then
		Floppy
		Dialog
	    else
		Flash
		Dialog
	    fi
	    Dialog
	    ;;
	1)
	    Dialog
	    ;;
	255)
	    #Dialog
	    exit
	    ;;
    esac
}

SetSerial
Dialog